<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simple"
    nsURI="http:///simple" nsPrefix="simple">
  <eClassifiers xsi:type="ecore:EClass" name="Base">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="cref=contents"/>
      <details key="cref=insides"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insides" upperBound="-1"
        eType="#//Inside" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="cref=withins"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="withins" upperBound="-1"
        eType="#//Within" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Within">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
      <details key="cref=wi1s"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wi1s" upperBound="-1" eType="#//Wi1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inside">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
      <details key="cref=intos"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intos" upperBound="-1"
        eType="#//Into" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Into">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
      <details key="cref=deeps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deeps" upperBound="-1"
        eType="#//Deep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deep">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wi1">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
      <details key="cref=wi2s"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wi2s" upperBound="-1" eType="#//Wi2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wi2">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
