<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adt101" nsURI="http://adt101" nsPrefix="_adt101">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameUnicity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="nameUnicity" value="bindings->isUnique(name)&#xD;&#xA;and&#xD;&#xA;components->isUnique(name)&#xD;&#xA;and&#xD;&#xA;interfaces->isUnique(name)&#xD;&#xA;"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=name" value="_"/>
      <details key="cref=requiredInterfaces" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="#//Required" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Required">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//AbstractComponent">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="pov" value="_"/>
      <details key="cont=Component.subComponents" value="_"/>
      <details key="kref=subComponents" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
        eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicComponent" eSuperTypes="#//AbstractComponent">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
