<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compmultinher"
    nsURI="http://compmultinher.v0" nsPrefix="compmultinher">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ks" upperBound="-1" eType="#//K"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=cs" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eAnnotations source="diagraph">
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="#//B">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=es" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es" upperBound="-1" eType="#//E"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F" eSuperTypes="#//D">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=gs"/>
      <details key="kref=hs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gs" upperBound="-1" eType="#//G"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hs" upperBound="-1" eType="#//H"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I" eSuperTypes="#//F #//K">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cont=A.bs"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=ls"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ls" upperBound="-1" eType="#//L"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
