<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebnf101"
    nsURI="http://swt.informatik.uni-mannheim.de/ebnfmm" nsPrefix="_ebnf101">
   <eAnnotations source="diagen">
    <details key="knownas=ebnf"/>
    <details key="origin=http://swt.informatik.uni-mannheim.de/ebnfmm"/>
    <details key="leftparent=nil" value=""/>
    <details key="rightparent=nil" value=""/>
    <details key="requires=nil" value=""/>
    <details key="context=textual dsl"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EBNFDescription">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" ordered="false"
        upperBound="-1" eType="#//NonTerminal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminal">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionList" lowerBound="1"
        upperBound="-1" eType="#//Symbol" containment="true" eOpposite="#//Symbol/containingNonTerminal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingNonTerminal"
        eType="#//NonTerminal" eOpposite="#//NonTerminal/definitionList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingControl" eType="#//Control"
        eOpposite="#//Control/definitionList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminalString" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionList" upperBound="-1"
        eType="#//Symbol" containment="true" eOpposite="#//Symbol/containingControl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminalReference" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonTerminal" lowerBound="1"
        eType="#//NonTerminal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialSequence" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Except" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="except" lowerBound="1"
        eType="#//Symbol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choose" eSuperTypes="#//Control"/>
</ecore:EPackage>
