<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="error5"
    nsURI="http://error5" nsPrefix="_error5">
  <eClassifiers xsi:type="ecore:EClass" name="X">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xcs" upperBound="-1" eType="#//C"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ps" upperBound="-1" eType="#//P"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zs" eType="#//Z" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ys" upperBound="-1" eType="#//Y"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="w" eType="#//W"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//B">
    <eAnnotations source="diagraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//C">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is" upperBound="-1" eType="#//I"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" abstract="true" eSuperTypes="#//G">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M" eSuperTypes="#//G">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=mcs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mcs" upperBound="-1" eType="#//C"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ml1" upperBound="-1" eType="#//L1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N" eSuperTypes="#//M">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="J" eSuperTypes="#//A">
    <eAnnotations source="diagraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P" eSuperTypes="#//N">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=ks"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//A"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ks" eType="#//K"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="js" upperBound="-1" eType="#//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Q" eSuperTypes="#//P">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l2s" upperBound="-1" eType="#//L2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I" eSuperTypes="#//G">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L1">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="label=id1"/>
      <details key="label=id2"/>
      <details key="cont=M.ml1"/>
      <details key="lsrc=l1m"/>
      <details key="ltrg=l1c"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l1c" eType="#//C"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l1m" eType="#//M"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K" eSuperTypes="#//J">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L2">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="label=l1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l2q" eType="#//Q"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l2k" eType="#//K"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="l1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="l2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Z">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=z1"/>
      <details key="label=z2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Y">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="W">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L3" eSuperTypes="#//L1">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="ltrg=l3i"/>
      <details key="cont=M.ml1"/>
      <details key="lsrc=l1m"/>
      <details key="ltrg=l3i"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l3i" eType="#//I"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L4" eSuperTypes="#//L1">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="ltrg=l4z"/>
      <details key="lsrc=l4p"/>
      <details key="cont=M.ml1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l4z" eType="#//Z"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l4p" eType="#//P"/>
  </eClassifiers>
</ecore:EPackage>
