<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="errstatechart101" nsURI="http://errstatechart101" nsPrefix="_errstatechart101">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="nav:vstate" value="_"/>
      <details key="cref=variables" value="_"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="pov" value="_"/>
      <details key="view=vstate" value="_"/>
      <details key="cont=State.substates" value="_"/>
      <details key="cref=variables" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="diagraph">
      <details key="link" value="_"/>
      <details key="label=name" value="_"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="link" value="_"/>
      <details key="label=name" value="_"/>
      <details key="view=vstate" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=name" value="_"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=name" value="_"/>
      <details key="view=vstate" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateChart" eSuperTypes="#//State">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="pov" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substates" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
