<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="facebook104" nsURI="http://facebook104" nsPrefix="_facebook104">
  <eClassifiers xsi:type="ecore:EClass" name="Facebook">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="pov" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communities" upperBound="-1"
        eType="#//Community" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uris" upperBound="-1" eType="#//Uri"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="kref=posts" value="_"/>
      <details key="ref=communities" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Friendship" containment="true" eOpposite="#//Friendship/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communities" upperBound="-1"
        eType="#//Community"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posts" upperBound="-1"
        eType="#//Post" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Friendship">
    <eAnnotations source="diagraph">
      <details key="link" value="_"/>
      <details key="cont=Member.relations" value="_"/>
      <details key="lsrc=from" value="_"/>
      <details key="ltrg=to" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Member"
        eOpposite="#//Member/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Member"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="since" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pending" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="kref=members" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Community" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eAnnotations source="diagraph">
      <details key="link" value="_"/>
      <details key="cont=Member.comments" value="_"/>
      <details key="lsrc=from" value="_"/>
      <details key="ltrg=to" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Member"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Post"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Like" eSuperTypes="#//Post">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="ref=likeUris" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="likeUris" upperBound="-1"
        eType="#//Uri"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dislike" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uri">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
