<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iml2"
    nsURI="http://www.isoe.lgi2p.ema.fr/gmf/example/iml2" nsPrefix="iml2">
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Type">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cont=Namespace.types" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true" eOpposite="#//Reference/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//Type">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cont=Namespace.types" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
      <details key="cont=Namespace.nested" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nested" upperBound="-1"
        eType="#//Namespace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="link" value=""/>
      <details key="cont=Entity.references" value=""/>
      <details key="lsrc=from" value=""/>
      <details key="ltrg=type" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Entity"
        eOpposite="#//Entity/references"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cont=Entity.attributes" value=""/>
      <details key="komp=Entity.*:figureEmbedded" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//Datatype"/>
  </eClassifiers>
</ecore:EPackage>
