<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="inherlink"
    nsURI="http://inherlink/1.0" nsPrefix="inherlink">
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ks" upperBound="-1" eType="#//K"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ms" upperBound="-1" eType="#//M"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xs" upperBound="-1" eType="#//X"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ns" upperBound="-1" eType="#//N"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R" abstract="true" eSuperTypes="#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="X" eSuperTypes="#//L"/>
  <eClassifiers xsi:type="ecore:EClass" name="Y" eSuperTypes="#//R">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ps" upperBound="-1" eType="#//P"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gs" upperBound="-1" eType="#//G"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ts" upperBound="-1" eType="#//T"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M" eSuperTypes="#//L"/>
  <eClassifiers xsi:type="ecore:EClass" name="N" eSuperTypes="#//R"/>
  <eClassifiers xsi:type="ecore:EClass" name="K" eSuperTypes="#//R">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ws" upperBound="-1" eType="#//W"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="#//Y" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="W" eSuperTypes="#//L"/>
  <eClassifiers xsi:type="ecore:EClass" name="L" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" upperBound="-1" eType="#//A"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" eType="#//R"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" eType="#//L"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gs" upperBound="-1" eType="#//G"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ts" eType="#//T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G"/>
  <eClassifiers xsi:type="ecore:EClass" name="T"/>
</ecore:EPackage>
