<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="inher104"
    nsURI="http://inher104" nsPrefix="_inher104">
  <eAnnotations source="diagen">
    <details key="knownas=simple world"/>
    <details key="origin=http://org.isoe.fr"/>
    <details key="leftparent=nil" value=""/>
    <details key="rightparent=nil" value=""/>
    <details key="requires=nil" value=""/>
    <details key="context=startup"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Commerce">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vente" eType="#//Ventes"
        containment="true" eOpposite="#//Ventes/vcommerce"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="administration" eType="#//Administration"
        containment="true" eOpposite="#//Administration/acommerce"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwventes"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwadministration"/>
      <details key="labels=nom:prix"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantStock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commune">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwadministration"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePostal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ventes" eSuperTypes="#//Nommable">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="cont=Commerce.vente"/>
      <details key="nav:vwventes"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwventes"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vadmin" eType="#//Administration"
        eOpposite="#//Administration/ventes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vcommerce" eType="#//Commerce"
        eOpposite="#//Commerce/vente"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Administration" eSuperTypes="#//Nommable">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="nav:vwadministration"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwadministration"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communes" upperBound="-1"
        eType="#//Commune" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ventes" eType="#//Ventes"
        containment="true" eOpposite="#//Ventes/vadmin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acommerce" eType="#//Commerce"
        eOpposite="#//Commerce/administration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nommable" abstract="true">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=nom"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwventes"/>
      <details key="label=nom"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwadministration"/>
      <details key="label=nom"/>
      <details key="kref=articles"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" upperBound="-1"
        eType="#//Article" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
