<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ktest206"
    nsURI="http://ktest206" nsPrefix="_ktest206">
  <eClassifiers xsi:type="ecore:EClass" name="B" abstract="true" eSuperTypes="#//N">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameUnicity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="nameUnicity" value="bindings->isUnique(name)&#xD;&#xA;and&#xD;&#xA;components->isUnique(name)&#xD;&#xA;and&#xD;&#xA;interfaces->isUnique(name)&#xD;&#xA;"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=cs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" abstract="true" eSuperTypes="#//B">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=ds"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ds" upperBound="-1" eType="#//D"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="X" eSuperTypes="#//Y">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ws" upperBound="-1" eType="#//W"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Y" abstract="true" eSuperTypes="#//A">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es" upperBound="-1" eType="#//E"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="#//N">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N">
    <eAnnotations source="diagraph">
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="W" eSuperTypes="#//N">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=vs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vs" upperBound="-1" eType="#//V"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="V" eSuperTypes="#//Y">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
