<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="layered"
    nsURI="http://diagraph.test.layered.v0" nsPrefix="playered">
  <eClassifiers xsi:type="ecore:EClass" name="MySystem" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
      <details key="cref=myElements" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myElements" upperBound="-1"
        eType="#//MyElements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetReference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyElements" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
