<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multiview3"
    nsURI="http://sample.multiview3" nsPrefix="multiview3">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
      <details key="cref=bs" value=""/>
      <details key="cref=es" value=""/>
      <details key="cref=aks" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es" upperBound="-1" eType="#//E"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aks" upperBound="-1" eType="#//K"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=cs" value=""/>
      <details key="pov:sub1" value=""/>
      <details key="ref=bfs" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bfs" eType="#//F"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=hs" value=""/>
      <details key="ref=ks" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hs" upperBound="-1" eType="#//H"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ks" upperBound="-1" eType="#//K"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cref=fs" value=""/>
      <details key="pov:sub2" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fs" upperBound="-1" eType="#//F"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ws" upperBound="-1" eType="#//W"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="kref=ms" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ms" upperBound="-1" eType="#//M"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="W" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="link" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wc" eType="#//C"/>
  </eClassifiers>
</ecore:EPackage>
