<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multiview904"
    nsURI="http://multiview904" nsPrefix="_multiview904">
  <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//State"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralView" eType="#//Structure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nomenclatures" upperBound="-1"
        eType="#//Nomenclature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nomenclature" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Nomenclature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="cont=Structure.state"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
