<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multiview101"
    nsURI="http://multiview101" nsPrefix="_multiview101">
  <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="nav:behavior"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="view=behavior"/>
      <details key="cref=states"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralView" eType="#//Structure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kinds" upperBound="-1"
        eType="#//StateKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="view=behavior"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateKind" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//StateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=behavior"/>
      <details key="cref=substates"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substates" upperBound="-1"
        eType="#//Substates" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="#//StateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Substates" eSuperTypes="#//State">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=behavior"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="lsrc=from"/>
      <details key="ltrg=to"/>
      <details key="view=behavior"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//State"/>
  </eClassifiers>
</ecore:EPackage>
