<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multiview4"
    nsURI="http://sample.multiview4" nsPrefix="multiview4">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
      <details key="cref=bs" value=""/>
      <details key="cref=es" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es" upperBound="-1" eType="#//E"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
      <details key="cref=cs" value=""/>
      <details key="view=sub1"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="nav:sub1"/>
      <details key="cref=cs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=sub1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="view=sub1"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="view=sub2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="cref=fs" value=""/>
      <details key="pov" value=""/>
      <details key="view=sub2"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="nav:sub2"/>
      <details key="cref=fs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fs" upperBound="-1" eType="#//F"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=sub2"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
