<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ref3" nsURI="http://www.isoe.lgi2p.ema.fr/gmf/example/ref3" nsPrefix="ref3">
  <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="//T">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N" eSuperTypes="//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="pov" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ts" upperBound="-1" eType="//T" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" upperBound="-1" eType="//A" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="//B" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="T" eSuperTypes="//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="ref=ds" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ds" upperBound="-1" eType="//D"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="ref=ds" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ds" upperBound="-1" eType="//D"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="//Named //D">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ds" eType="//D"/>
  </eClassifiers>
</ecore:EPackage>
