<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stuff"
    nsURI="http://stuff" nsPrefix="_stuff">
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="things" upperBound="-1"
        eType="#//Thing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=others"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="others" upperBound="-1"
        eType="#//Thing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stuff" eSuperTypes="#//Thing">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=bars"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foos" upperBound="-1" eType="#//Foo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bars" upperBound="-1" eType="#//Bar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="cont=Stuff.foos"/>
      <details key="lsrc=src"/>
      <details key="ltrg=trg"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//Stuff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" eType="#//Thing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bar" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=baz"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baz" upperBound="-1" eType="#//Baz"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Baz" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
