<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="system913"
    nsURI="http://system913" nsPrefix="_system913">
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node" value=""/>
      <details key="nav:functionalView"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="view=functionalView"/>
      <details key="cref=functionalArchitecture"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalArchitecture"
        upperBound="-1" eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workbench" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemView" eType="#//System"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kinds" upperBound="-1"
        eType="#//FunctionKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name" value=""/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="view=functionalView"/>
      <details key="label=name"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=functionDecomposition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionKind" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//FunctionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Named">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="view=functionalView"/>
      <details key="nav:functionDecomposition"/>
      <details key="cont=System.functionalArchitecture"/>
      <details key="ref=associations"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="ref=associations"/>
      <details key="view=functionDecomposition"/>
      <details key="cont=Function.decompositions"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decompositions" upperBound="-1"
        eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" eType="#//FunctionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" eType="#//Function"/>
  </eClassifiers>
</ecore:EPackage>
