<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tank202"
    nsURI="http://tank202" nsPrefix="_tank202">
  <eAnnotations source="diagen">
    <details key="knownas=simple world"/>
    <details key="origin=http://org.isoe.fr"/>
    <details key="leftparent=nil" value=""/>
    <details key="rightparent=nil" value=""/>
    <details key="requires=nil" value=""/>
    <details key="context=startup"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LevelRegulation">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tank" eType="#//Tank" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" eType="#//Sink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controler" eType="#//Controler"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valve" eType="#//Valve"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tank" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="afx=sensor"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controler" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=fromSensor"/>
      <details key="ref=toValve"/>
      <details key="label=pGain"/>
      <details key="label=iGain"/>
      <details key="label=dGain"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromSensor" eType="#//Sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toValve" eType="#//Valve"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pGain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iGain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dGain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valve" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=from"/>
      <details key="ref=to"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Tank"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Sink"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" upperBound="-1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="nav:vwsource"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
      <details key="view=vwsource"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" eType="#//Flow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sink" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="diagraph">
      <details key="label=name"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="view=vwsource"/>
      <details key="label=name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//NamedElement">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="cont=Source.flow"/>
      <details key="lsrc=from"/>
      <details key="ltrg=to"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwsource"/>
      <details key="cref=history"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Tank"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="view=vwsource"/>
      <details key="label=value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
