<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test101"
    nsURI="http://test101" nsPrefix="_test101">
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="pov"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" upperBound="-1" eType="#//A"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ds" upperBound="-1" eType="#//D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l1s" upperBound="-1" eType="#//L1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//B">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=name"/>
      <details key="ref=bs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
      <details key="ref=gs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gs" eType="#//G"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="#//G">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="ref=fs"/>
      <details key="ref=gs"/>
      <details key="cref=ns"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fs" upperBound="-1" eType="#//F"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gs" upperBound="-1" eType="#//G"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ns" upperBound="-1" eType="#//N"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E" eSuperTypes="#//D">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="cref=js"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="js" upperBound="-1" eType="#//J"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F" eSuperTypes="#//E">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="cref=qs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qs" upperBound="-1" eType="#//Q"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G" eSuperTypes="#//M">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="kref=is"/>
      <details key="cref=ks"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is" upperBound="-1" eType="#//I"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ks" upperBound="-1" eType="#//K"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L1">
    <eAnnotations source="diagraph">
      <details key="link"/>
      <details key="lsrc=from"/>
      <details key="ltrg=to"/>
      <details key="cont=C.l1s"/>
      <details key="label=since"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="since" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//B"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//G"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I">
    <eAnnotations source="diagraph">
      <details key="node"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="J">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=ids"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ids" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Q">
    <eAnnotations source="diagraph">
      <details key="node"/>
      <details key="label=id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
