<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yy5" nsURI="http://yy5" nsPrefix="_yy5">
  <eAnnotations source="diagen">
    <details key="knownas=State Chart"/>
    <details key="origin=nil"/>
    <details key="leftparent=statemachine" value=""/>
    <details key="rightparent=nil" value=""/>
    <details key="requires=nil" value=""/>
    <details key="context=behavior" value="kewords={fsm,behavior,state,transition,recursive,action}&#xD;&#xA;related={state*}&#xD;&#xA;Finite State Machine with composite states&#xD;&#xA;Actions associated to states"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameUnicity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="nameUnicity" value="bindings->isUnique(name)&#xD;&#xA;and&#xD;&#xA;components->isUnique(name)&#xD;&#xA;and&#xD;&#xA;interfaces->isUnique(name)&#xD;&#xA;"/>
    </eAnnotations>
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="pov" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foos" upperBound="-1" eType="#//Foo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bizes" upperBound="-1"
        eType="#//Biz" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
      <details key="kref=bars" value="_"/>
      <details key="kref=boos" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bars" upperBound="-1" eType="#//Bar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boos" upperBound="-1" eType="#//Boo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bar" abstract="true">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Baz" eSuperTypes="#//Bar">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boo">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Biz" abstract="true">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
      <details key="kref=boums" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boums" upperBound="-1"
        eType="#//Boum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bille" eSuperTypes="#//Biz">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boum">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
      <details key="label=id" value="_"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Zig" eSuperTypes="#//Biz">
    <eAnnotations source="diagraph">
      <details key="node" value="_"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
